#!/bin/bash

echo "========================================"
echo "蓝队CTF平台故障排查脚本"
echo "========================================"
echo ""

echo "📋 请依次执行以下命令进行排查："
echo ""

echo "1️⃣ 检查服务是否启动"
echo "---"
echo "docker compose ps"
echo "---"
echo ""

echo "2️⃣ 查看容器日志"
echo "---"
echo "docker compose logs"
echo "---"
echo ""

echo "3️⃣ 检查端口监听"
echo "---"
echo "netstat -tlnp | grep -E '5173|3001'"
echo "或"
echo "ss -tlnp | grep -E '5173|3001'"
echo "---"
echo ""

echo "4️⃣ 检查防火墙"
echo "---"
echo "systemctl status firewalld"
echo "firewall-cmd --list-ports"
echo "---"
echo ""

echo "5️⃣ 检查Docker状态"
echo "---"
echo "systemctl status docker"
echo "docker ps -a"
echo "---"
echo ""

echo "6️⃣ 如果容器未启动，重新部署"
echo "---"
echo "cd /root/blueteamctf-cn"
echo "docker compose down"
echo "docker compose up -d --build"
echo "---"
echo ""

echo "7️⃣ 开放防火墙端口（如果需要）"
echo "---"
echo "firewall-cmd --permanent --add-port=5173/tcp"
echo "firewall-cmd --permanent --add-port=3001/tcp"
echo "firewall-cmd --reload"
echo "---"
echo ""

echo "8️⃣ 检查阿里云安全组"
echo "如果使用阿里云ECS，需要在控制台配置安全组："
echo "  - 入方向：允许 TCP 5173"
echo "  - 入方向：允许 TCP 3001"
echo ""

echo "========================================"
echo "常见问题解决方案"
echo "========================================"
echo ""

echo "❌ 问题1: 容器无法启动"
echo "解决："
echo "  docker compose down"
echo "  docker system prune -f"
echo "  docker compose up -d --build"
echo ""

echo "❌ 问题2: 端口被占用"
echo "解决："
echo "  lsof -i :5173"
echo "  kill -9 <PID>"
echo ""

echo "❌ 问题3: npm安装失败"
echo "解决："
echo "  # 检查.npmrc是否存在"
echo "  cat .npmrc"
echo "  # 手动配置镜像"
echo "  npm config set registry https://registry.npmmirror.com"
echo ""

echo "❌ 问题4: 网络无法访问"
echo "解决："
echo "  # 检查是否监听在0.0.0.0"
echo "  netstat -tlnp | grep 5173"
echo "  # 应该看到 0.0.0.0:5173，而不是 127.0.0.1:5173"
echo ""

echo "========================================"
echo ""
