#!/bin/bash

echo "========================================"
echo "CTF Platform Troubleshooting Script"
echo "========================================"
echo ""

echo "Please run the following commands to diagnose:"
echo ""

echo "1) Check if services are running"
echo "---"
echo "docker compose ps"
echo "---"
echo ""

echo "2) View container logs"
echo "---"
echo "docker compose logs"
echo "---"
echo ""

echo "3) Check port listening"
echo "---"
echo "netstat -tlnp | grep -E '5173|3001'"
echo "or"
echo "ss -tlnp | grep -E '5173|3001'"
echo "---"
echo ""

echo "4) Check firewall"
echo "---"
echo "systemctl status firewalld"
echo "firewall-cmd --list-ports"
echo "---"
echo ""

echo "5) Check Docker status"
echo "---"
echo "systemctl status docker"
echo "docker ps -a"
echo "---"
echo ""

echo "6) Redeploy if containers are not running"
echo "---"
echo "cd /root/blueteamctf-cn"
echo "docker compose down"
echo "docker compose up -d --build"
echo "---"
echo ""

echo "7) Open firewall ports if needed"
echo "---"
echo "firewall-cmd --permanent --add-port=5173/tcp"
echo "firewall-cmd --permanent --add-port=3001/tcp"
echo "firewall-cmd --reload"
echo "---"
echo ""

echo "8) Check cloud security group"
echo "If using Aliyun ECS, configure security group in console:"
echo "  - Inbound: Allow TCP 5173"
echo "  - Inbound: Allow TCP 3001"
echo ""

echo "========================================"
echo "Common Solutions"
echo "========================================"
echo ""

echo "Issue 1: Containers cannot start"
echo "Fix:"
echo "  docker compose down"
echo "  docker system prune -f"
echo "  docker compose up -d --build"
echo ""

echo "Issue 2: Port already in use"
echo "Fix:"
echo "  lsof -i :5173"
echo "  kill -9 <PID>"
echo ""

echo "Issue 3: npm install failed"
echo "Fix:"
echo "  # Check if .npmrc exists"
echo "  cat .npmrc"
echo "  # Manually set mirror"
echo "  npm config set registry https://registry.npmmirror.com"
echo ""

echo "Issue 4: Network unreachable"
echo "Fix:"
echo "  # Check if listening on 0.0.0.0"
echo "  netstat -tlnp | grep 5173"
echo "  # Should see 0.0.0.0:5173, not 127.0.0.1:5173"
echo ""

echo "========================================"
echo ""